"""The personal pass: forms of words Migaku already knows, and freebies (2026-08-24).

The user's instruction: some of these words are forms of words already known — remove
them from the list, and the obvious ones like "Kilo" with them. Four classes, each a rule
plus a HAND-REVIEWED keep-list — every rule here over-fires on homographs, and the review
is the half that makes it safe. Re-running is deterministic; a new word entering a rule's
range lands in the cut file with its reason, where the review can catch it.

  A — capitalised nominalisation whose base ADJECTIVE is a Migaku row: Beste←gut,
      Neues←neu, Tote←tot, Junge←jung (yes — the July decision protected Junge's corpus
      tokens from crediting `jung`; this is the user's later decision that they do not
      need to study it). Keep-list: lexicalised homographs the rule cannot see —
      Gewissen (совесть, not "the certain one"), Taube (голубь), Sitte (обычай),
      Platte, Freier (клиент), Wilderer (браконьер), Klammer, Schauer…
  B — lowercase adj/adv that the dictionary files as a declension or degree of a Migaku
      adjective: weiter←weit, lange←lang, blöde←blöd. This deliberately reverses the
      earlier "lange/weiter recovered" call: they ARE forms of words the user knows, which is
      exactly what the instruction names.
  C — verb that is simultaneously the dictionary's form of a Migaku verb: gefallen←
      fallen, geraten←raten, plus preterite-plural ghosts (riefen, schliefen — rare
      homograph lemmas that absorb rufen's and schlafen's past tenses). Keep-list: real
      verbs whose edge is a Konjunktiv-II accident — betrügen (betragen!), gelangen
      (gelingen), rasten (rasen), tränken (trinken), bürgen (bergen), vorführen…
  D — transparent internationalisms («кило»-class): candidates are generated by an
      English-cognate match (wordfreq zipf ≥ 3.3 over k→c/z→c/-ie→-y/-ik→-ic/… variants)
      and were reviewed word by word; KEEP_D is the false-friend half of that review —
      Teller (тарелка, not a bank teller), List (хитрость), Taste (клавиша), After
      (анус!), Provision (комиссионные), Rat-class traps live here. The match is a
      candidate feed, never a verdict.

Runs AFTER blend.py, rewrites de-living-german.tsv in place (the pipeline's idiom —
polish2 does the same to de-spoken-final) and appends its cuts to de-spoken-cut.tsv.
"""
import csv
import os
import re
import sys

D = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(D))
sys.path.insert(0, D)
import foldlib
from wordfreq import zipf_frequency

from lib.config import settings

dic = foldlib.Dict(D)
MIG = {r[0].lower() for r in csv.reader(
    open(os.path.join(settings.BACKUP_DIR, "migaku", "de.csv"), encoding="utf-8"))
    if r and r[0] != "dictForm"}

KEEP_A = {"Gewissen", "Taube", "Sitte", "Platte", "Flotte", "Eifer", "Raucher",
          "Schauer", "Klammer", "Matte", "Plane", "Ringer", "Heiler", "Knappe",
          "Kühler", "Schiefer", "Freier", "Wilderer"}
KEEP_C = {"betrügen", "gelangen", "vorführen", "rasten", "tränken", "bürgen",
          "zwängen", "unterlegen", "trügen", "runden"}
# The false-friend half of the D review: same spelling, different word.
KEEP_D = {"links", "Teller", "drum", "regieren", "frieren", "Ross", "Regal", "Stall",
          "Dose", "Kaution", "Parker", "Schale", "Glanz", "stricken", "Wade", "Turner",
          "Pest", "Tara", "Latte", "spendieren", "herb", "List", "doll", "Pole",
          "First", "Schaum", "Bach", "Laie", "Zaum", "Limo", "Slip", "Sage", "Fund",
          "Lori", "Elle", "Base", "Provision", "Taste", "lose", "Heck", "Wink",
          "Roller", "Lanze", "Matte", "Plane", "Drilling", "Grips", "bang", "listen",
          "Trunk", "Lump", "Porto", "tags", "Bran", "Gram", "Schall", "Tang",
          "genieren", "raven", "fade", "sezieren", "rings", "Kanzel", "More",
          "liieren", "Sang", "Most", "Messing", "Barren", "Queue", "Mole", "dezent",
          "Charge", "Sims", "Inland", "gieren", "Schaft", "Isch", "After",
          "Promotion", "Hole", "Saum", "Sole", "Butt", "grassieren", "Stuck", "quick",
          "Dust", "kitten", "x-mal", "Wisch", "karieren", "Chose", "Pensum", "franko",
          "radieren", "kross", "Tide", "Stride", "Aye-Aye", "Sore", "small", "Rank",
          "lasch", "apart", "Blender", "Binder", "Heap", "Pups", "Gaze", "UCLA",
          "Stokes", "Zane"}
# Hand additions the rules cannot see: Migaku's own lemma of the word itself (`elter`
# IS the user's Eltern row), colloquial contractions of Migaku adverbs (drüber = darüber), and
# `Besonderes`, whose base lives in Migaku as the ADVERB besonders.
CUT_EXTRA = {
    "Eltern": "Migaku's own lemma of this word (elter), marked known",
    "Besonderes": "nominalisation of besonders, in Migaku",
    "drüber": "colloquial contraction of darüber, in Migaku",
    "drum": "colloquial contraction of darum, in Migaku",
    "rauf": "colloquial contraction of hinauf, in Migaku",
    "drunter": "colloquial contraction of darunter, in Migaku",
}


def base_adj(stem):
    """stem → the base adjective it declines (fremd→fremd, Best→gut via beste)."""
    for s in (stem, dic.spell.get(stem, stem).lower(), deumlaut(stem)):
        if "adj" in dic.head.get(s, ()):
            return s
        for key in (s, s + "e"):
            for t in dic.fof[key].get("adj", ()):
                return t.lower()
            for t in dic.both[key].get("adj", ()):
                return t.lower()
            if key in dic.degree:
                return sorted(dic.degree[key])[0].lower()
    return None


def d_variants(w):
    l = w.lower()
    vs = {l, l.replace("k", "c"), l.replace("z", "c"),
          l.replace("k", "c").replace("z", "c"), l.replace("sch", "sh"),
          l.replace("ß", "ss")}
    more = set()
    for v in vs:
        for a, b in (("ie", "y"), ("ik", "ic"), ("ik", "ics"), ("ismus", "ism"),
                     ("ität", "ity"), ("in", "ine"), ("ur", "ure"), ("ös", "ous"),
                     ("anz", "ance"), ("enz", "ence"), ("ieren", "ate"),
                     ("ieren", ""), ("iv", "ive"), ("um", ""),
                     # -isch is Greco-Latin -ic: allergisch, chronisch, zynisch —
                     # the 2026-08-25 review found ~100 of these sitting past the
                     # first pass because the transform was missing
                     ("istisch", "istic"), ("isch", "ic"), ("isch", "ical")):
            if v.endswith(a):
                more.add(v[:-len(a)] + b)
    return vs | more


# ---- class E: derived from a place name — nationality/place adjectives, demonyms,
# language nouns. `grep korea` was the report that forced it: koreanisch #1797,
# Koreaner, Koreanerin, Koreanisch, nordkoreanisch, Nordkoreaner, Südkoreaner — seven
# rows all free once you can read Korea, exactly as кореец/корейский are. The base set
# is an EXPLICIT geography whitelist: matching against the corpus's proper-name cuts
# was tried first and gave ~80 false hits out of 237 — film names four letters long
# reached through every suffix (`Bäcker`←Back, `Beere`←Beer, `Donner`←Donna,
# `Kante`←Kant), and en-wikt's gazetteer would be worse (it knows a town called
# Buchen). The stem machinery covers German's suffix juggling (polnisch→Polen,
# Ire→Irland, Türke→Türkei, sächsisch→Sachsen via de-umlaut); KEEP_E is the reviewed
# residue where a real word still collides with real geography (`Galle`←Gallien,
# `Bremse`←Bremen, `Haifisch`←Haifa); the Franzose family has no derivable stem
# (Frankreich) and is cut by hand in HAND_OBVIOUS.
GEO = {"korea", "südkorea", "nordkorea", "japan", "china", "spanien", "italien",
       "russland", "schweden", "ungarn", "ägypten", "australien", "schottland",
       "österreich", "holland", "island", "rumänien", "thailand", "armenien", "irak",
       "iran", "albanien", "serbien", "sachsen", "afghanistan", "sibirien", "tibet",
       "pakistan", "texas", "hawaii", "marokko", "mexiko", "brasilien", "kanada",
       "norwegen", "kuba", "berlin", "wien", "hamburg", "vietnam", "preußen",
       "belgien", "troja", "boston", "genf", "kolumbien", "athen", "türkei",
       "argentinien", "siam", "burgund", "osteuropa", "westeuropa", "europa",
       "amerika", "südamerika", "nordamerika", "afrika", "südafrika", "asien",
       "indien", "indiana", "frankfurt", "thrakien", "algerien", "nürnberg",
       "guinea", "sizilien", "haiti", "prag", "warschau", "kreta", "chicago",
       "sparta", "jamaika", "brandenburg", "britannien", "münchen", "mailand",
       "krakau", "danzig", "mongolei", "potsdam", "panama", "bayern", "malta",
       "kroatien", "salzburg", "gallien", "persien", "sudan", "kambodscha",
       "nigeria", "washington", "graz", "griechenland", "irland", "polen",
       "dänemark", "finnland", "portugal", "ukraine", "bulgarien", "slowakei",
       "tschechien", "luxemburg", "israel", "libanon", "syrien", "jordanien",
       "tunesien", "libyen", "äthiopien", "kenia", "ghana", "somalia", "venezuela",
       "chile", "peru", "bolivien", "ecuador", "paraguay", "uruguay", "korsika",
       "sardinien", "katalonien", "andalusien", "provence", "bretagne", "flandern",
       "hessen", "schwaben", "westfalen", "thüringen", "franken", "schweiz",
       "skandinavien", "balkan", "orient", "karibik", "arabien", "saudi-arabien",
       "neuseeland", "ozeanien", "mikronesien", "polynesien", "indonesien",
       "malaysia", "philippinen", "birma", "laos", "nepal", "bhutan", "mongolen",
       "kaukasus", "georgien", "aserbaidschan", "kasachstan", "usbekistan",
       "turkmenistan", "moskau", "petersburg", "kiew", "paris", "london", "rom",
       "madrid", "lissabon", "amsterdam", "brüssel", "stockholm", "oslo",
       "kopenhagen", "helsinki", "budapest", "bukarest", "belgrad", "zagreb",
       "sofia", "istanbul", "ankara", "kairo", "bagdad", "teheran", "kabul",
       "tokio", "peking", "schanghai", "bombay", "delhi", "seoul", "hanoi",
       "bangkok", "manila", "jakarta", "sydney", "melbourne", "toronto",
       "montreal", "chile", "havanna", "lima", "bogotá", "caracas", "köln",
       "stuttgart", "dresden", "leipzig", "hannover", "bremen", "kiel", "bonn",
       "basel", "zürich", "bern", "innsbruck", "linz", "venedig", "florenz",
       "neapel", "turin", "genua", "palermo", "sevilla", "barcelona", "valencia",
       "porto", "marseille", "lyon", "bordeaux", "nizza", "genua"}
E_SUFFIXES = ("isch", "ische", "er", "erin", "ese", "esin", "e", "in")
E_TAILS = ("", "n", "en", "ien", "land", "ei", "a", "o", "enland", "reich", "emark")
KEEP_E = {"Haifisch", "Weißfisch", "Galle", "Spanne", "Spange", "Spanner", "Bremse",
          "Polente", "Genüge", "Schotter", "Übersee", "Kieler", "Sparte"}


def deumlaut(s):
    return s.replace("ä", "a").replace("ö", "o").replace("ü", "u")


def place_base(w, names):
    for suf in E_SUFFIXES:
        if not w.lower().endswith(suf) or len(w) - len(suf) < 4:
            continue
        s = w.lower()[:-len(suf)]
        for stem in {s, s[:-1], s[:-2], deumlaut(s), deumlaut(s)[:-1]}:
            for tail in E_TAILS:
                # a bare stem must be a plausible name on its own; with a tail three
                # letters suffice — polnisch reaches Polen as pol+en
                if len(stem) < (4 if tail == "" else 3):
                    continue
                if stem + tail in names:
                    return stem + tail
    return None


# Names that slipped past the corpus name filter wearing a dictionary sense (die Tara
# is a real word — the 1,598-per-million `Tara` in subtitles is a character).
NAME_JUNK = {"Tara", "Lori", "Zane", "Bran", "Stokes", "UCLA", "Parker"}
# Reviewed by hand: obvious to a Russian+English reader, but no transform reaches them —
# the Franzose family has no derivable stem, Кretin/Knute/Portwein ARE the Russian words.
HAND_OBVIOUS = {"Franzose", "Französin", "französisch", "Französisch", "Waliser",
                "Krise", "Granate", "Terrasse", "Palme", "Grazie", "Elektriker",
                "Allee", "Portwein", "Narzisse", "Terrier", "Ellipse", "Kretin",
                "Chinin", "Paraffin", "Kamelie", "Marinade", "Sommelier",
                "Grenadier", "Maxime", "Amazone", "Violine", "Barbier", "Knute",
                "Markise", "Karaffe", "Kantine", "Marge", "Normanne", "Samariter",
                "Lutheraner", "Teenagerin", "Caprice", "Latein", "Portier"}

rows = [l.rstrip("\n").split("\t")
        for l in open(f"{D}/de-living-german.tsv", encoding="utf-8")][1:]
cut = {}
for r in rows:
    w, pos = r[1], r[7]
    lo = w.lower()
    if w in CUT_EXTRA:
        cut[w] = CUT_EXTRA[w]
        continue
    if w in NAME_JUNK:
        cut[w] = "a proper name the filters missed"
        continue
    if w in HAND_OBVIOUS:
        cut[w] = "transparent internationalism (reviewed by hand)"
        continue
    if w not in KEEP_E:
        b = place_base(w, GEO)
        if b:
            cut[w] = f"derived from the place name {b.capitalize()}"
            continue
    if w[:1].isupper() and pos in ("NOUN", "PROPN", "ADJ") and w not in KEEP_A:
        m = re.match(r"^(.*?)(e|er|es|en)$", w)
        if m and len(m.group(1)) >= 3:
            b = base_adj(m.group(1).lower())
            if b and b in MIG:
                cut[w] = f"nominalisation of {b}, in Migaku"
                continue
    if pos in ("ADJ", "ADV") and w[:1].islower():
        ts = {t.lower() for t in
              dic.fof[lo].get("adj", set()) | dic.both[lo].get("adj", set())
              | dic.fof[lo].get("adv", set()) | dic.both[lo].get("adv", set())
              | dic.degree.get(lo, set())}
        hit = sorted(ts & MIG)
        if hit:
            cut[w] = f"declension/degree of {hit[0]}, in Migaku"
            continue
    if pos == "VERB" and w not in KEEP_C:
        ts = {t.lower() for t in
              dic.fof[lo].get("verb", set()) | dic.both[lo].get("verb", set())}
        hit = sorted(ts & MIG)
        if hit:
            cut[w] = f"verb form of {hit[0]}, in Migaku"
            continue
    if len(w) >= 4 and w not in KEEP_D:
        best = max(((v, zipf_frequency(v, "en")) for v in d_variants(w)),
                   key=lambda t: t[1])
        if best[1] >= 3.3:
            cut[w] = f"transparent internationalism (~{best[0]})"

# What this pass removes leaves the study list but is worth shelves of its own — it is
# vocabulary the user gets for free, not vocabulary that never existed: the
# internationalisms in one file, the forms/nominalisations/contractions of Migaku words
# in the other. Both in list order, i.e. by frequency.
with open(f"{D}/de-internationalisms.txt", "w", encoding="utf-8") as f:
    for r in rows:
        if cut.get(r[1], "").startswith(("transparent internationalism",
                                         "derived from the place name")):
            f.write(r[1] + "\n")
with open(f"{D}/de-known-forms.txt", "w", encoding="utf-8") as f:
    for r in rows:
        if cut.get(r[1], "").startswith(("nominalisation of", "declension/degree of",
                                         "verb form of", "colloquial contraction of",
                                         "Migaku's own lemma")):
            f.write(r[1] + "\n")

keep = [r for r in rows if r[1] not in cut]
with open(f"{D}/de-living-german.tsv", "w", encoding="utf-8") as f:
    f.write("rank\tlemma\tliving_score\tfilm_pm\teveryday_pm\tweb_pm\tfilm_skew"
            "\tpos\twiktionary_pos\n")
    for i, r in enumerate(keep, 1):
        f.write("\t".join([str(i)] + r[1:]) + "\n")
with open(f"{D}/de-spoken-cut.tsv", "a", encoding="utf-8") as f:
    for r in rows:
        if r[1] in cut:
            f.write(f"{r[1]}\t{r[2]}\t{cut[r[1]]}\n")

from collections import defaultdict
g = defaultdict(list)
for r in rows:
    if r[1] in cut:
        g[cut[r[1]].split(" of ")[0].split(" (")[0]].append(r[1])
print(f"list {len(rows):,} → cutting {len(cut):,} → kept {len(keep):,}", file=sys.stderr)
for k, v in sorted(g.items(), key=lambda kv: -len(kv[1])):
    print(f"  {len(v):>4}  {k}: {', '.join(v[:18])}{' …' if len(v) > 18 else ''}",
          file=sys.stderr)
